Hero Page
ubc-biomod/biomod2024 pull request #12
Opened 2024-11-04 20:54 UTC by JosephDeng317

Hero with animated 3D model, scroll lock, and animated text. The mobile view could be improved but works for now

2024-11-04 21:56 UTC, JosephDeng317 commented
https://github.com/user-attachments/assets/4b8ffca7-f916-493e-af5b-ed8ae610b34b

2024-11-05 19:30 UTC, CarsonKiibi requested changes
Looks great and the component appears to be working as intended other than the video issue I mentioned (perhaps it only happens on my device).

The main source of unexpected behavior comes from the video for some reason, I'm not sure why but I assume the 3js component is trying to resize based on the space the fullscreen video takes up and just doesn't revert. I think serena already implemented the video component so I'd assume you can just remove it and when we add the final one we have to ensure fullscreen is disabled or maybe we can find a fix for the fullscreen issue.

Just consider adding a components folder to match the other components. I'll let Minh review too and make sure it's all good. We likely won't have time to learn 3js so we probably won't be able to provide a comprehensive review on the 3js parts but I can say it looks really nice :)

2024-11-05 19:30 UTC, CarsonKiibi commented on src/content/docs/hero.jsx
> +        {/* Centered YouTube Iframe */}
Hero should not contain youtube video as well, I believe serena implemented the video frame already

2024-11-05 19:30 UTC, CarsonKiibi commented on src/content/docs/hero.jsx
> +              allowFullScreen
allowFullScreen seems to break the model size. To replicate, full screen the youtube video and get out of fullscreen. For me the fridge got smaller and squeezed (narrower on x axis)

2024-11-05 19:30 UTC, CarsonKiibi commented on src/content/docs/hero.jsx
> +// Import necessary libraries
Components should be in a src/components folder (see main branch or carson/footer branch).

2024-11-15 09:25 UTC, IcedTea2K approved these changes
;-;

2024-11-15 09:25 UTC, IcedTea2K commented on src/content/docs/hero.jsx
> +      </div>
You can remove this part, as Serena's already delivered her PR.

2024-11-15 09:35 UTC, merged